name: Update AdGuard Extra

on:
  schedule:
    - cron: '0 0 */2 * *'  # every 2 days
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Download latest AdGuard Extra
        run: |
          curl -sL https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js -o adguard-extra.js

      - name: Remove extra UserScript metadata block with sed
        run: |
          sed '1,/\/\/ ==\/UserScript==/d' adguard-extra.js > clean.js
          mv clean.js adguard-extra.js


      - name: Wrap adguard-extra.js with header and footer
        run: |
          echo 'adguard-extra.js text/javascript' > temp.js
          echo '(function() {' >> temp.js
          cat adguard-extra.js >> temp.js
          echo '})();' >> temp.js
          mv temp.js adguard-extra.js
          
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '16'

      - name: Deobfuscate AdGuard Extra script
        run: npx javascript-deobfuscator adguard-extra.user.js --output adguard-extra.deobfuscated.js

      - name: Set up Git identity
        run: |
          git config user.name "Auto Updater"
          git config user.email "auto-updater@users.noreply.github.com"

      - name: Commit and push if updated
        run: |
          if ! git diff --quiet; then
            git add adguard-extra.js
            git commit -m "Update AdGuard Extra script"
            git push
          else
            echo "No changes to commit"
          fi
