name: Update AdGuard Extra Scriplet

on:
  schedule:
    - cron: '0 0 */2 * *'  # every 2 days
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Download latest AdGuard Extra
        run: |
          curl -sL https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js -o source.js

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '16'

      - name: Install and run de4js
        # Corrected: Execute the script directly from the local node_modules bin directory.
        run: |
          npm install de4js
          ./node_modules/.bin/de4js -s source.js -o deobfuscated.js

      - name: Inspect deobfuscated file
        # This step helps you see if the deobfuscation was successful
        run: |
          echo "--- First 50 lines of deobfuscated.js ---"
          head -n 50 deobfuscated.js
          echo "-------------------------------------------"

      - name: Format deobfuscated code into a scriplet
        run: |
          # 1. Remove the UserScript metadata block from the deobfuscated file
          sed '1,/\/\/ ==\/UserScript==/d' deobfuscated.js > clean.js

          # 2. Wrap the cleaned code in an IIFE
          {
            echo '(function() {'
            cat clean.js
            echo '})();'
          } > adguard-extra-scriplet.js

      - name: Set up Git identity
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@users.noreply.github.com"

      - name: Commit and push if updated
        run: |
          git add adguard-extra-scriplet.js
          
          if ! git diff --staged --quiet; then
            git commit -m "Update AdGuard Extra scriplet"
            git push
          else
            echo "No changes to commit"
          fi
