name: Update AdGuard Extra Scriplet

on:
  schedule:
    - cron: '0 0 */2 * *'  # every 2 days
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Download latest AdGuard Extra
        run: |
          curl -sL https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js -o source.js

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '16'

      - name: Deobfuscate the script
        # Takes the original downloaded file and outputs a deobfuscated version
        run: npx javascript-deobfuscator source.js --output deobfuscated.js

      - name: Format deobfuscated code into a scriplet
        run: |
          # 1. Remove the UserScript metadata block from the deobfuscated file
          sed '1,/\/\/ ==\/UserScript==/d' deobfuscated.js > clean.js

          # 2. Wrap the cleaned code in an IIFE (Immediately Invoked Function Expression)
          # This creates the final, self-contained scriplet
          {
            echo '(function() {'
            cat clean.js
            echo '})();'
          } > adguard-extra-scriplet.js

      - name: Set up Git identity
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@users.noreply.github.com"

      - name: Commit and push if updated
        run: |
          # Add the final scriplet file to the staging area
          git add adguard-extra-scriplet.js
          
          # Check if there are any staged changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Update AdGuard Extra scriplet"
            git push
          else
            echo "No changes to commit"
          fi
